config/routes.rb
DimamarkusCom::Application.routes.draw do

  root :to => 'static_pages#home'

  match 'web' => 'static_pages#web'
  match 'blog' => 'static_pages#blog'
  match 'music' => 'static_pages#music'
  match 'about' => 'static_pages#about'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def web
  end

  def blog
  end

  def music
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper


	# Returns the full title on a per-page basis.
	def full_title(page_title)
		base_title = "Dima Markus"
		if page_title.empty?
			base_title
		else
			"#{base_title} | #{page_title}"
		end
	end


end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <div class="row">
    <div class="large-4 columns">
      <ul>
        <li>Web Design</li>
        <li>Blog</li>
        <li>Music</li>
        <li>About</li>
      </ul>
    </div>
    <div class="large-4 columns">
      Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolorem, voluptate, suscipit architecto animi consequuntur ea cupiditate dolores sit vel excepturi quis quidem eveniet magnam tempore in! Similique expedita officiis placeat.
    </div>
    <div class="large-4 columns">
      Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut quo consequuntur modi deleniti ad? Iste earum sit dignissimos nobis est perspiciatis amet! Earum, incidunt rem repellendus dignissimos. Ut, corporis, quam.
    </div>
  </div>

  <div id="copyright">
    <p>
      © 2013 DMITRIY MARKUS
    </p>
  </div>
</footer>

app/views/layouts/_header.html.erb
<!-- <header>
  <div class="row">
	  <div class="small-2 columns" id="hamburger">
	    <a href="#menu">&#9776;</a>
	  </div>
	  <div class="small-10 small-centered columns">
	    <h1 class="banner"><%= link_to "Dima Markus", root_path %></h1>
	  </div>
  </div>
</header> -->

<header>
	<a href="#menu" id="hamburger">&#9776;</a>
	<h1><%= link_to 'Dima Markus', root_path, id: "banner"%></h1>
</header>

app/views/layouts/_mobile-nav.html.erb
<nav id="menu">
  <ul>
    <li class="Selected" ><%= link_to 'Dima Markus', root_path, id: "home-link" %></li>
    <li>
    	<div class="livicon" data-name="globe"></div>
    	<%= link_to 'Web Design', web_path %>
    </li>
    <li>
    	<div class="livicon" data-name="notebook"></div>
    	<%= link_to 'Blog', blog_path %>
    </li>
    <li>
     	<div class="livicon" data-name="music"></div>
    	<%= link_to 'Music', music_path %>
    </li>
    <li>
    	<div class="livicon" data-name="user"></div>	
    	<%= link_to 'About', about_path %>
    </li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

<!--   	<title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title> -->

    <title><%= full_title(yield(:title)) %></title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
  
    <div id="page">

      <%= render 'layouts/header' %>

      <div class="content">
        <%= yield %>
      </div>
      
      <%= render 'layouts/footer' %>

      <%= render 'layouts/mobile-nav' %>

    </div>
    
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Me') %>


	<h2>About Me</h2>
<p>
	Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloribus, molestiae, maiores, eius voluptatum dicta corporis consequatur doloremque quod earum atque unde veritatis aspernatur laborum quo incidunt corrupti magnam pariatur reiciendis.
</p>

app/views/static_pages/blog.html.erb
<% provide(:title, 'Blog') %>


	<h2>Blog</h2>
<p>
	Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloribus, molestiae, maiores, eius voluptatum dicta corporis consequatur doloremque quod earum atque unde veritatis aspernatur laborum quo incidunt corrupti magnam pariatur reiciendis. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Alias, eaque quibusdam nobis quaerat fugiat molestias similique harum saepe molestiae corporis magnam et cumque nostrum eius aliquid repellendus placeat ut ipsa!
</p>
<p>
	Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloribus, molestiae, maiores, eius voluptatum dicta corporis consequatur doloremque quod earum atque unde veritatis aspernatur laborum quo incidunt corrupti magnam pariatur reiciendis. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officia, consequatur, fugiat maxime atque in vitae dignissimos a aperiam modi iste hic ullam quam tempora aut suscipit omnis sunt at veritatis.
</p>

<p>
	Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloribus, molestiae, maiores, eius voluptatum dicta corporis consequatur doloremque quod earum atque unde veritatis aspernatur laborum quo incidunt corrupti magnam pariatur reiciendis. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reprehenderit, quae, labore sint provident commodi similique nam consectetur delectus praesentium laboriosam pariatur modi numquam quis consequuntur facere id nemo! Molestiae, ullam!
</p>
<p>
	Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloribus, molestiae, maiores, eius voluptatum dicta corporis consequatur doloremque quod earum atque unde veritatis aspernatur laborum quo incidunt corrupti magnam pariatur reiciendis. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Alias, eaque quibusdam nobis quaerat fugiat molestias similique harum saepe molestiae corporis magnam et cumque nostrum eius aliquid repellendus placeat ut ipsa!
</p>
<p>
	Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloribus, molestiae, maiores, eius voluptatum dicta corporis consequatur doloremque quod earum atque unde veritatis aspernatur laborum quo incidunt corrupti magnam pariatur reiciendis. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officia, consequatur, fugiat maxime atque in vitae dignissimos a aperiam modi iste hic ullam quam tempora aut suscipit omnis sunt at veritatis.
</p>

<p>
	Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloribus, molestiae, maiores, eius voluptatum dicta corporis consequatur doloremque quod earum atque unde veritatis aspernatur laborum quo incidunt corrupti magnam pariatur reiciendis. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reprehenderit, quae, labore sint provident commodi similique nam consectetur delectus praesentium laboriosam pariatur modi numquam quis consequuntur facere id nemo! Molestiae, ullam!
</p>
<p>
	Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloribus, molestiae, maiores, eius voluptatum dicta corporis consequatur doloremque quod earum atque unde veritatis aspernatur laborum quo incidunt corrupti magnam pariatur reiciendis. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Alias, eaque quibusdam nobis quaerat fugiat molestias similique harum saepe molestiae corporis magnam et cumque nostrum eius aliquid repellendus placeat ut ipsa!
</p>
<p>
	Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloribus, molestiae, maiores, eius voluptatum dicta corporis consequatur doloremque quod earum atque unde veritatis aspernatur laborum quo incidunt corrupti magnam pariatur reiciendis. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officia, consequatur, fugiat maxime atque in vitae dignissimos a aperiam modi iste hic ullam quam tempora aut suscipit omnis sunt at veritatis.
</p>

<p>
	Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloribus, molestiae, maiores, eius voluptatum dicta corporis consequatur doloremque quod earum atque unde veritatis aspernatur laborum quo incidunt corrupti magnam pariatur reiciendis. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reprehenderit, quae, labore sint provident commodi similique nam consectetur delectus praesentium laboriosam pariatur modi numquam quis consequuntur facere id nemo! Molestiae, ullam!
</p>

app/views/static_pages/home.html.erb
<section>
	<div class="row">
		<p class="small-12 small-centered columns" id="my-blurb">
			A showcase for my interests.
		</p>
	</div>
</section>

<section>

	<div class="row">
		<article class="small-12 large-6 columns">
			<div>
				<a href=""><h2>Web Design</h2></a>
			</div>
			<div>
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reiciendis, quia, exercitationem, quasi repellendus ipsa hic omnis iste iusto error praesentium rerum dolorem itaque fugiat pariatur totam. Pariatur expedita inventore voluptate.</p>
			</div>
		</article>

		<article class="small-12 large-6 columns">
			<div>
				<a href=""><h2>Blog</h2></a>
			</div>
			<div>
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Impedit, explicabo, rem, tempora distinctio unde illo corporis iure molestias enim natus beatae accusantium quam ea maiores culpa aliquam itaque eius doloremque!</p>
			</div>
		</article>
	</div>


	<div class="row">
		<article class="small-12 large-6 columns">
			<div>
				<a href=""><h2>Music</h2></a>
			</div>
			<div>
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Veniam, incidunt repellat nihil deserunt architecto ratione rerum illum doloremque possimus aut? Doloremque, deserunt, expedita qui repudiandae blanditiis mollitia possimus fugit perferendis.</p>
			</div>
		</article>

		<article class="small-12 large-6 columns">
			<div>
				<a href=""><h2>About Me</h2></a>
			</div>
			<div>
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quasi, distinctio natus repellendus tempora excepturi facilis numquam assumenda atque reprehenderit cum officia ut omnis a voluptatum nostrum ex illum explicabo ad.</p>
			</div>
		</article>
	</div>

</section>

app/views/static_pages/music.html.erb
<% provide(:title, 'Music') %>


	<h2>Music</h2>
<p>
	Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloribus, molestiae, maiores, eius voluptatum dicta corporis consequatur doloremque quod earum atque unde veritatis aspernatur laborum quo incidunt corrupti magnam pariatur reiciendis.
</p>

app/views/static_pages/web.html.erb
<% provide(:title, 'Web Design') %>

	<h2>Web Design</h2>
<p>
	Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloribus, molestiae, maiores, eius voluptatum dicta corporis consequatur doloremque quod earum atque unde veritatis aspernatur laborum quo incidunt corrupti magnam pariatur reiciendis.
</p>